apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secret-provider
  namespace: three-tier
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/301954988003/secrets/DATABASE_URL/versions/latest"
        path: "DATABASE_URL"