apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: three-tier
  annotations:
    iam.gke.io/gcp-service-account: gke-backend-sa@project-40d105bf-bb2b-4bf6-b9f.iam.gserviceaccount.com