apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.backend.serviceAccount.gcpServiceAccount | quote }}
